### ISSUE TITLE
throw ERR_FS_FILE_TOO_LARGE for a zip of 2GB 

### ISSUE THREAD

**Issue by pemryan** [sanori/node-unzip-mbcs#7]
fs.js:318
      throw new ERR_FS_FILE_TOO_LARGE(size);
      ^

RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2288420255) is greater than possible Buffer: 2147483647 bytes
    at tryCreateBuffer (fs.js:318:13)
    at Object.readFileSync (fs.js:354:14)
    at new module.exports (/usr/local/lib/node_modules/unzip-mbcs/node_modules/adm-zip/zipFile.js:18:17)
    at new module.exports (/usr/local/lib/node_modules/unzip-mbcs/node_modules/adm-zip/adm-zip.js:20:11)
    at Object.extractSync (/usr/local/lib/node_modules/unzip-mbcs/unzip-mbcs.js:33:13)
    at Command.<anonymous> (/usr/local/lib/node_modules/unzip-mbcs/cli.js:32:13)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/unzip-mbcs/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/usr/local/lib/node_modules/unzip-mbcs/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/unzip-mbcs/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/usr/local/lib/node_modules/unzip-mbcs/node_modules/commander/index.js:970:12)

**Comment by pemryan** [comment]
inactive.
